Basic operation like mat mult and pauli operations

In [ ]:
from IPython.display import display
from qiskit import __version__
import numpy as np
ket0 = np.array([[1],[0]]) #|0>
ket1=np.array([[0],[1]]) #|1>
print(ket0/2+ket1/2)
M1 = np.array([[1, 1], [0, 0]]) 
M2 = np.array([[1, 0], [0, 1]])
M = M1 / 2 + M2 / 2
print(M)
print(np.matmul(M1, ket1))
print(np.matmul(M1, M2))
print(np.matmul(M, M))
#Making prettier output
from qiskit.visualization import array_to_latex

display(array_to_latex(np.matmul(M1, ket1)))
display(array_to_latex(np.matmul(M1, M2)))
display(array_to_latex(np.matmul(M, M)))



[[0.5]
 [0.5]]
[[1.  0.5]
 [0.  0.5]]
[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [1]:
from qiskit.quantum_info import Statevector
from numpy import sqrt

u = Statevector([1 / sqrt(2), 1 / sqrt(2)])
v = Statevector([(1 + 2.0j) / 3, -2 / 3])
w = Statevector([1 / 3, 2 / 3])

In [2]:
display(u.draw("text"))
display(u.draw("latex"))
print(u.draw("latex_source"))

[0.70710678+0.j,0.70710678+0.j]

<IPython.core.display.Latex object>

\frac{\sqrt{2}}{2} |0\rangle+\frac{\sqrt{2}}{2} |1\rangle


To check if given vector is valid quantum vector ie Eucleadian Num


In [3]:
display(u.is_valid())
display(w.is_valid())

True

False